#!/usr/bin/env bash

set -euo pipefail

GHN_DIR="$(dirname "$(greadlink -f "$0")")"

function fetch_events() {
  # cat /tmp/all-notifications |
  hub api notifications --obey-ratelimit -XGET --field all=true |
    jq -r '
    .[] |
      [.subject.url,
       .updated_at,
       .subject.type,
       .unread,
       .reason,
       .repository.owner.login,
       .repository.name,
       .subject.title
      ] | join("|")'
}

function events_for_fzf() {
  fetch_events |
    sort -t'|' -k4,4 -k2,2 -r |
    awk -F '|' -f $GHN_DIR/notifications-for-fzf.awk
}

function event_endpoint() {
  awk '{ printf $1 }' <<<$1
}
export -f event_endpoint

function event_preview() {
  endpoint=$(event_endpoint $1)
  hub api "$endpoint" |
    jq -r '.body'
}
export -f event_preview

event_line=$(
  events_for_fzf |
    fzf --reverse --ansi \
      --with-nth 2.. \
      --preview="event_preview {}" \
      --preview-window=:wrap:hidden \
      --header "ctrl-p toggles preview" \
      --bind="ctrl-p:toggle-preview"
)

event_html_url=$(
  event_endpoint $event_line |
    xargs hub api |
    jq -r '.html_url'
)

firefox-container --name Work "$event_html_url"
