#!/usr/bin/env bash

set -euo pipefail

DIR="$(dirname "$(greadlink -f "$0")")"

function fetch_events() {
  # cat /tmp/all-notifications |
  hub api notifications --obey-ratelimit -XGET --field all=true |
    jq -r '
    .[] |
      [.subject.url,
       .updated_at,
       .subject.type,
       .unread,
       .reason,
       .repository.owner.login,
       .repository.name,
       .subject.title
      ] | join("|")'
}

function events_for_fzf() {
  sort -t'|' -k4,4 -k2,2 -r |
    awk -F '|' -f $DIR/notifications-for-fzf.awk
}

events=$(fetch_events)

event_id=$(
  echo "$events" |
    events_for_fzf |
    fzf --reverse --ansi |
    awk '{ printf substr($1, 2, 999) }'
)

event_endpoint=$(
  awk -F '|' -v event_id=$event_id '$1 ~ "/" event_id "$" { print $1 }' <<<$events
)

event_html_url=$(
  hub api "$event_endpoint" |
    jq -r '.html_url'
)

firefox-container --name Work "$event_html_url"
