#!/usr/bin/env bash

set -euo pipefail

GHN_DIR="${GHN_DIR:-$(dirname "$(greadlink -f "$0")")}"
GHN_CONFIG=~/.config/ghn/config.sh
GHN_OPEN_CMD=open

if [ -r $GHN_CONFIG ]; then
  source $GHN_CONFIG
fi

function fetch_events() {
  hub api notifications -XGET --field all=true |
    jq -r '
    .[] |
      [.subject.url,
       .updated_at,
       .subject.type,
       .unread,
       .reason,
       .repository.owner.login,
       .repository.name,
       .subject.title
      ] | join("|")'
}

function events_for_fzf() {
  fetch_events |
    sort -t'|' -k4,4 -k2,2 -r |
    awk -F '|' -f $GHN_DIR/common.awk -f $GHN_DIR/notifications-for-fzf.awk
}

function html_url() {
  sed \
    -e 's|//api\.github\.com/repos/|//github.com/|' \
    -e 's|/pulls/|/pull/|' \
    <<<$1
}
export -f html_url

function preview_issue() {
  url=$(html_url $endpoint)
  hub api graphql --flat --field query=@$GHN_DIR/issue.graphql --field url=$url |
    awk -f $GHN_DIR/common.awk -f $GHN_DIR/issue-details.awk |
    fold -s -w $FZF_PREVIEW_COLUMNS
}
export -f preview_issue

function preview_pr() {
  url=$(html_url $endpoint)
  hub api graphql --flat --field query=@$GHN_DIR/pullrequest.graphql --field url=$url |
    awk -f $GHN_DIR/common.awk -f $GHN_DIR/pullrequest-details.awk |
    fold -s -w $FZF_PREVIEW_COLUMNS
}
export -f preview_pr

function event_preview() {
  endpoint=$(cut -d ' ' -f 1 <<<$1)
  etype=$(cut -d ' ' -f 2 <<<$1)
  if [ $etype = "Issue" ]; then
    preview_issue
  else
    preview_pr
  fi
}
export -f event_preview

event_line=$(
  events_for_fzf |
    fzf --reverse --ansi \
      --with-nth 3.. \
      --preview="GHN_DIR=$GHN_DIR event_preview {}" \
      --preview-window=:wrap:hidden \
      --header "ctrl-p toggles preview" \
      --bind="ctrl-p:toggle-preview,shift-up:preview-up,shift-down:preview-down"
)

event_html_url=$(html_url $(cut -d ' ' -f 1 <<<$event_line))

$GHN_OPEN_CMD "$event_html_url"
